# Generated by Django 2.2.3 on 2019-07-10 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabeblishments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('street', models.CharField(max_length=100, verbose_name='Rua')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numero')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('city', models.CharField(max_length=100, verbose_name='Estado')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': ('Estabelecimento',),
                'verbose_name_plural': 'Estabelecimentos',
            },
        ),
    ]
